Consult_Company/Pages/Admin/ManageRoles.cshtml.cs
using Consult_Company.Data;
using Consult_Company.Model.Admin;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consult_Company.Pages.Admin
{
    public class ManageRolesModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageRolesModel(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [BindProperty]
        public string userId { get; set; }
        [BindProperty]
        public List<ManageUserRoles> userRoles { get; set; }
        public async Task OnGetAsync(string userId)
        {

            this.userRoles = await GetAllAsync(userId);
        }
                
        public async Task<IActionResult> OnPostUpdate(string userId)
        {
            
            var user = await _userManager.FindByIdAsync(userId);
            
            if (user == null)
            {
                return Page();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return Page();
            }
            result = await _userManager.AddToRolesAsync(user, userRoles.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return Page();
            }
            return RedirectToPage("./RoleEdit",  userId );
        }
        public async Task<List<ManageUserRoles>> GetAllAsync(string userId)
        {
           var items = new List<ManageUserRoles>();
            ViewData["userId"] = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {


            }
            ViewData["UserName"] = user.UserName;

            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new ManageUserRoles
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                items.Add(userRolesViewModel);
            }
            return items;
        }
    }
}

Consult_Company/Pages/Admin/RoleEdit.cshtml.cs
using Consult_Company.Data;
using Consult_Company.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Consult_Company.Pages.Admin
{
    public class RoleEditModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        

        public RoleEditModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            
        }
        public List<UserRolesView> userRolesView = new List<UserRolesView>();
        public async Task<IActionResult> OnGet()
        {
            var users = await _userManager.Users.ToListAsync();

            foreach (ApplicationUser user in users)
            {
                var thisviewModel = new UserRolesView();
                thisviewModel.UserId = user.Id;
                thisviewModel.UserName = user.UserName;
                thisviewModel.Email = user.Email;
                thisviewModel.FirstName = user.firstName;
                thisviewModel.LastName = user.lastName;
                thisviewModel.Roles = await GetUserRoles(user);
                userRolesView.Add(thisviewModel);

            }

            return Page();
        }
        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
        
    }
}

Consult_Company/Pages/Admin/admin.cshtml.cs
using Consult_Company.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Consult_Company.Pages.Admin
{
    public class adminModel : PageModel
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public List<IdentityRole> roles { get; set; }
        public adminModel( RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
            
        }
        
        public void OnGet()
        {
            roles = roleManager.Roles.ToList();
        }

        
        public async Task<IActionResult> OnPostCreate([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToPage();
                
            }
            return Page();
        }
        public async Task<IActionResult> OnPostDelete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToPage();
                
            }
            else
                ModelState.AddModelError("", "No role found");
            return Page();
        }

    }
}

Consult_Company/Pages/Admin/ManageRoles.cshtml
@page
@model Consult_Company.Pages.Admin.ManageRolesModel
@{
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage User Roles</h2>
            Add/Remove Roles for User / @ViewData["UserName"].
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.userRoles.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model.userRoles[i].RoleId" />
                    <input type="hidden" asp-for="@Model.userRoles[i].RoleName" />
                    <input asp-for="@Model.userRoles[i].Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model.userRoles[i].Selected">
                        @Model.userRoles[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            
            <input type="submit" value="Submit"  asp-page-handler="Update" asp-route-userId =@ViewData["userId"] class="btn btn-primary" style="width:auto"/>
            <a asp-page="./RoleEdit" class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

Consult_Company/Pages/Admin/RoleEdit.cshtml
@page
@model Consult_Company.Pages.Admin.RoleEditModel
@{
}
<form method="post">
<h1>User Roles</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.userRolesView)
        {
        <tr>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Email</td>
            <td>@string.Join(" , ", user.Roles.ToList())</td>
            <td>
                <a class="btn btn-primary" asp-page="ManageRoles" asp-route-userId="@user.UserId">Manage Roles</a>
            </td>
        </tr>
        }
    </tbody>
</table>
</form>

Consult_Company/Pages/Admin/admin.cshtml
@page
@model Consult_Company.Pages.Admin.adminModel
@{
}
<h1>Role Manager</h1>
<form asp-page-handler="Create" method="post">
    <div class="input-group">
        <input name="name" class="form-control w-25">
        <span class="input-group-btn">
            <button type="submit" class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Role</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.roles)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    <form asp-page-handler="Delete" method="post">
                        
                        <button type="submit" class="btn btn-primary" name="id" value="@item.Id" >Delete</button>                                                    
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>